language: php
sudo: false
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  allow_failures:
  - php: 5.3
  - php: 5.4
  - php: 5.6
  - php: 7.0
env:
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.2
  - MAGENTO_VERSION=magento-ce-1.9.2.1
  - MAGENTO_VERSION=magento-ce-1.9.2.0
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
  global:
  - secure: gSCCyq7SjazzlDtxV2wftzlXZq1jUxQplBCxqczwvrYLVmKaMaTx+R8YSpR6oFTrrX4IE2Wetml2bpPr/WIrynQbGyCbLYQrxz1iBHu0dYCIJ6oVF4Vs/E/bEDRQPoDWHH6PhomHjLra8FpM4QUgSpPCZkuU48/uLH9dm8zZ3H1d6N8AanWa2SKLq7BQGEKmJeF2sh6iZ57E7Ij10qXA1woh2jy7SSXg83XFBRU7hwUn4s0mfXcvkMNUxVCWsuk0waQV3Auki0Db3MqxFH+hKbsKhdL1qvKV5OKYjGAt5IeOL/ZFy3WT1twHQ6UwDlXu6JpTvHBrj424luHF6umQhLSqNink7XN3zSOvQrxKfQShT2iKTrXeslrVaXSBstPK0Gu6gEBbAEPeY7rtpWN12aybFe8tunYsRXZStKIrQDRzRWGEUMpSe81m4Il+Hdi646d47QdJEOd2Bysl0+HCl3sk5YOouPo50Z9GEAuwubfUqzhR7p41osLDG9hfvNLYosne+zpeVL4cYcOWypbr+EqGYNNUKQG6JKKyJRFYeoKZOQRqUCJln32++NKYWsx0OEHsvenLbK7B0k30hRR5TfIUAGAq+T2ROuMuXa7Sfxz86OFfRD11LjKExkJvOyyDQ8ZouG66Vf+ToiygTcgKluwBzKCanXe2kton3ePZbjc=
  - secure: AYRwRvon5rqs+Y1jZtsqO5O1uS/W+aTTpgYWw8G/dTHGmpPyiq+rsJif6OeOVaqintVZqbVYLA6gO6KvmP0ntJnKbZVfhC1x3e920/JEVhmIt0SROtblbn9KHqYMjq2WdxdhmX80xgXVvWQMjSaSV+Y8B/aRBbYLTlVwz0GMU1ybOKMsOORxLZslA4zXKx6n7/+mjgQGThcewPIsiu8xpcHEFe8LU2p9hXXpKk3sebHZkbAWkjS8V5+2zWnYlnkKHKAhDXYlWfcDxIYkCueSA1VoZbjJ0c+hapP3t6kWeByQONf+BtlOl1LUoePWQ70nQtgamlPKt8Qvh0Jig/wEOBcMpW8ukH+eN3bCh3/05x4OL0aKBBOrwq31u0hNtk0Bf3GF8JJokPSXById9WK5rp0Misag+f47PfIxgDr0IgXjh97wA6aDh/ly6BP6eS2Omjj53XbbNMqQPB2Snh1iwsuxVyYc944r1+iwwJkBBX8y1N37SrwtOeyuNuLQ4dcGLhdIUunmWXUYrst4Y0k0fHua9rhba9dktKI/FpB3pHxNHD+EMp2xzRozB9QS3prQwToZ1dZ2tP1/k6sY7GdH4nYMfMQlPa8zOMjK81kNlf7YZOGR0UWpMX0DuPpCxwBHgWJSZxbabE1+6PIE+ZSplF34k9b4fqeyM4vKgLEh/nw=
  - secure: TG5IBqJlWkwf5nuKG8xb3nW1OrgZ26f1P0nhwhT9cCnoW6oxbQpGxggjWnTGYt07xB4UOOXUOrvLAno5khsellCuLogJfPq5qq4xVrHfgDoNBQPzVA5rEuG91Tipzo8Sx/jipZ3S1lblAlv7oBfJCokYLHkSzPDH5ngBBKhiI21hlhkJG92sJgd6s710JlosAM3LEbljw/5v6AKsEYYnlJeSSNIr24eGtHfv+D4lvQp0CNTtdukYukzOw6x9tAWm5uo6B7TT+/gdUL/kY2aNF4Rl75AGBUrrEa5cjpoDqjRBy+Jyf5ihCaJe9DHg3IjMeufXuxEQYx3gd2j6m2+bYgVVZE/8V6vLMIO/VDGvIlvlpjUHNvkOFtuXayrOp7S+4pGJ5FWCo4qUCd37s4NMdeNa3TdsgCiFRSgibGlQIjXtXr/HqKZmKj0eqIYRBLG1JcJ+ATd3v7bRBeegdXA3+F6c+uuS1G6jtlRUPSr3K1WTjQj4HnR8Wf0n9A9GY70OUlHCgy3MTNFvj77Ks/bfqbAhbU5h70dsDXcm8GU+Fs4TBN5pTanKxzq8oRR5NAP6HyWjBd55qcvbhD+Loe+OgZaAHyY+K+PdJuYQAtOv7kf1f14KgkAz5CGdcfio/PCFzlDN17SyvLxXy6giE0hq/+kn9li4/ln+bMTuABEKVms=
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
notifications:
  slack:
    secure: Z3o2WzMoGYgVD/JFJQwAZb3eEcE+YHabPnjpdCIp4drN9v1jD6d3npdTdkvToE4jZX0Tl58tgjZsG79+E1zwUeofPLwKTr8BoTg6ngR1b431E+xJn1DpMSq1Eky/jlThYVBa1MzLN4L3Chzt6tRmasFq5wOB/mjcdzgdrld5PsqD0F290ZhUIdLMQwpsVU/yptt6J4bsyeg5fW4B3ihvTZHRX+hZ8wAXTvTv0u6WvpA5KTEpXbUZVIiz8LEr3v6aV1+ArGTlY120kVR68hHxoZsBK4O5KWHiXOLcjGXI/dDkQitFQ/U9mtQjF6SZwEeLb0a40xGfueSOx39uawn0nBhlEPToPntO88NYt/cl6WbSNXog032IrpZGpt4kdQ5GFma+QNHVLKf+W+6bplyymNfCYnRGs2el6wosu5JjZuu1Cv/xD4bY0wjIfj+OApooUG+HNZ7usn7/SxUPMnJ1BHqzmZYLlFYDIq1Bs0iyQffrvHYV4dzj9uyohaLXYCnu9f3DOoUqwVRcqu1Ea2q9DtjGHUt8b/xESKxGZxp5FCYLON0rG+BWUS744E9m38H3V8j55AbduCRu6eZN5hvDrUUQh/cOJSCogNL97wkHeHSycREqHInQlmUjim/dwHTTNzNz/YDZwFCoF8DesdLbOYlhGNhRigFN/3Um2CmZpUA=
