language: php
sudo: false
php:
- 5.4
- 5.5
- 5.6
- 7.0
matrix:
  fast_finish: true
  allow_failures:
  - env: MAGENTO_VERSION=magento-ce-1.9.1.1
  - php: 5.6
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
  - php: 7.0
    env: MAGENTO_VERSION=magento-mirror-1.8.1.0
env:
  global:
  - APPNAME=Ffuenf_CouponCodeCleaner
  - secure: aAo63Lm7hJ/ZF/xb0RYSg7YR7iiwvsKcsN8KhY5EJNYA4JQ2p5GOwzaLuAJHcoBXMD/0XqAMfJKG2x2qoqO6A636UvkkO1JWmxzBEfPrJWkcepiJIVuDCbhf1NChv8uPgZQrLR0m6m9S1KaG4us+XmxUGgNVlu/M9+W57y1IahqyGZZBSDEWp+MstpoBFuYj9eUhJRPOUTtoYLqaLjP00RoSkD4noAu3S3jtJHoxKnVuiNDJrTMEBqgj2XRPI0RMflM9Qk/Dh3u6gGguVsGygS6VkvXxEUSqVaf34aK/WgFCDlXAEUWSv+A+dCoTcbgk/0zkZW0GQZqzR4lJtnFWvpezj6n2TQ+sg5YJPuVM9oudCB0pvctqUUxUfJkjNmiRTe74R7QFg9Pu+7M2BS59abbcmF4dEzc5+jUnu3rpf3lUNfSks7OnCdKmCYefd8JqyeyFK7NZS+cg99lJwz5vvBIkB96gmDZ52smbkuVt6jCaOOSVL4BfkQhRm+FKmdxdCvfmZiKZ9yBQr6Ne/F5S7jtl5DHA9CiYy89h0LQgO1iuy/HxPyK0QVBXMhlltv4dzRiVKpbexrabp0GJzBqx0746ZTPCSu6lMkX0R0Iwej81S1SAt3ZYHui/PzhDJZPkRpOgtZqA+x3AOPxnYWcT2jqQKz9+Tk1FFfgfLI9GewU=
  - secure: d3Uc6B8yHsg+bYrhIN0Os+vTnkbp7S2bV3E9CwweQfUkN/Sl43gJfBjz9B+plM0GY2LV7CKVtN33dRXfGITdDpvIMaQX5v+aLncMxY3XSRWj9hkMV8N/yK4O63tstZxuc2nSLAZBlWPfmn8Ub9RLliR4HPEHVMM1T2JpXaS4RAPAfa+x5oc9EmGvFmUaUVgcyXK+ikKeRQB7/GTa8JadD1HORPeupT0MXDRbt1MCXXZH63U74RfXkVBStfoT0Ljr9mSqhEpxwzUwllOaI/gve/yjh9LO9M/sUcaB4aDMJFYjy84Ty43HVihcDUihCX+j1Ee10kAbRMSSuOI9mBeGwFmJlQ7QvbZypjze/82xZk3RY6VpcPqxAK5VTvyzVMX5+sfMb73BGyxMtyJilih6eZ9QUXW17vUT37wl+xRNtJwO3jNGqRtccpoP8BsVcf506/fVaitO+wUEjmKCaW650k90/Q5J8TZjFGLGPgEsifcgviTxulTX22osAJ/ajoPapyXKWrntk6UqbBTLi7UIhYM4a9r39PPDaBMEw4m7PNUi1eFxGPZvKThhTczZuRVMFK0MsSABBZqfwCqzDE7a4rmmKGwQLnAm33Z5qLHIIHLNIv3uN9wyrOhADAkubfAZJowOgSGgRrQH13WRI+B+GA9fFv+3p6oLys2FCHGErjw=
  matrix:
  - MAGENTO_VERSION=magento-ce-1.9.2.4
  - MAGENTO_VERSION=magento-ce-1.9.1.1
  - MAGENTO_VERSION=magento-mirror-1.8.1.0
  - MAGENTO_VERSION=magento-mirror-1.7.0.2
  - MAGENTO_VERSION=magento-mirror-1.6.2.0
before_script:
- composer self-update
- composer install --prefer-source
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/setup.sh
  | bash
before_deploy:
- gem install mime-types -v 2.6.2
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: l6Go9TaTd/itm9cCTEJDJ0OSGQJI4kbkF+6hWZb1YKtkpMjfeNU/SdX2LBql6FuOSbg3fE4JZTBbsNU4odW/YHm9PGsNiwfjhxeztljFRFULro/DGof/+/fgfbBQj8Optv7bVVfob6l/Kfddj7fmB1n0lW08DqtITJWqh2vz0937bO2+x8wkAUP/RKWVk+wEeTxF7c1JKgo5UgO6HkPdO5d4OwBFIGg4Xph8fLK8QMu87+tDIV0Q0P2bD8onMOWXIoNVKZn72Jlu6zi93BX2gTB71AKokXlBwLLfjPHktedzWCngD1w9ektZQwiG6Zr3AiyceasIOgOqqMw4T4twAH9Xx2tVLGXJjTLy5rsQ/oQlF5z42o+VOAPDzGrEgMSqxJFiE/NZbCk/NbnHekN3HwriK71XUMLyYExzJhvgxZ10oxNHgZdM0GUkWYm7QJWBVjs517w1zYoM9jba+rmLciG+6qAeaohMdvCsOv7kg/T3R6aPxGZ37PUdEyIURpLGsya0dLDQg0wgQ0rtad382FOBTSqyqM1jpQ3k2qp9iuIYNECGedhxzaxu0ZaU7WdBZ/V/08K1Ykk8BTYwkRzPm0JExrPlf2wQHuLPHWOCZZi2OU5Xi42lvovWWz53OKhgA/MNk8ZA9Hl6yUK3/hkKSTmo1oqZddUklO5CRwLTl2w=
notifications:
  slack:
    secure: cUkdKyClMCRh8YX7nzHr/EVIxhGCid9j1/765S7XFlBc4ju8yZSArGHuYNKcImuaCu7NW+iWVz3UORsLlv5rLAdI9hq5AndeqQRW96b9eSjHKTYFYhdK6rxEAsHfRFcr245z3EH0bGq+L7hTwpNZst/bvaC+1dFmgVBjfqK/xwX2Ffll0zHVgv+nXvFiQLsYeEhOsL0m8Mc6yNGP+VIkKBWdJyxuCTl+MAdo9T/oismUByfmmygGwx8L1Boj0WnO4LrHCb+MvyHznp0114I/uAHKrcMqnJzTG20/uLel9H5LaLDNwt9yCWyuYHgQHwA4bVEtew5CU30AzBGH1Fvth1ozhSLN39OsYRvjUv2frVn7XpSGsWBS3QtCIhG/bzLWLBUCafHB47UKbbdeLELU50lhDgRxq3k4PEHmHLkPIjptBqFdW93ubv1rp72HaBAqy6p9ojkYWfdSh3ywTraTvd1uXw03C1OPTQ4FM47/VE6fTEM032zsdEwXhuYlxP5G5a2ZNac5kAq0bQyN+JiKjIEWiJSvZg8vqPCYvcac2+YJkUhA6Bs19J6KN9APyb/SROawFPTzCfpECEIk3I9/Yl7Vx+guC/frYrF5NeVVX6JhpeAJ7HCu7h/IvYdQEJUO/m8WacIIqiO7Oukbl++4XKg0b7gHwCcrJAJXkdZdUwQ=
